# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-16 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=10)),
                ('pj_number', models.IntegerField(max_length=8)),
                ('nhif_number', models.CharField(max_length=20)),
                ('nssf_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Transgender')], max_length=1)),
                ('date_of_retirement', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
