# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Designation Name', max_length=20, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Employee First Name', max_length=20)),
                ('middle_name', models.CharField(help_text='Employee Middle Name', max_length=20)),
                ('last_name', models.CharField(help_text='Employee Surname Name', max_length=20)),
                ('id_number', models.CharField(help_text='Passport or National Identification Number', max_length=10)),
                ('pj_number', models.IntegerField(unique=True)),
                ('nhif_number', models.CharField(max_length=20, unique=True)),
                ('nssf_number', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Transgender')])),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('postal_address', models.CharField(blank=True, help_text='Postal Adddress', max_length=10, null=True)),
                ('home_country', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employees_profile_picture')),
            ],
            options={
                'ordering': ('pj_number',),
            },
        ),
        migrations.CreateModel(
            name='EmployeeDesignations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_apppointment', models.DateField()),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Designation')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
            ],
        ),
    ]
