# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email_address',
        ),
    ]
