# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-16 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Transgender')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pj_number',
            field=models.IntegerField(),
        ),
    ]
