# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-16 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20171216_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(help_text='Employee First Name', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_number',
            field=models.CharField(help_text='Passport or National Identification Number', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(help_text='Employee Surname Name', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(help_text='Employee Middle Name', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nhif_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nssf_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pj_number',
            field=models.IntegerField(unique=True),
        ),
    ]
