# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-16 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20171216_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Designation Name', max_length=20, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.DeleteModel(
            name='Designations',
        ),
        migrations.AddField(
            model_name='employee',
            name='designations',
            field=models.ManyToManyField(related_name='employees', to='employees.Designation'),
        ),
    ]
