# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-16 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20171216_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='designations',
            new_name='designation',
        ),
    ]
