# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-16 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20171216_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDesignations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_apppointment', models.DateField()),
                ('remarks', models.CharField(max_length=250)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Designation')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
        migrations.AddField(
            model_name='employeedesignations',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
    ]
