# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-16 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20171216_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedesignations',
            name='remarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
