# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20171216_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
